update texts set name="Synchro Material", desc="Select 1 face-up monster your opponent controls. If you Synchro Summon this turn, you can use the selected monster as a Synchro Material Monster. You cannot conduct your Battle Phase during the turn you activate this card." where id=14507213
;update texts set name="Red Nova", desc="If a Level 8 or higher Dragon-Type Synchro Monster is on the field, you can Special Summon this card (from your hand). You can only Special Summon ""Red Nova"" once per turn this way. If this card is sent to the Graveyard for a Synchro Summon that uses 2 or more Tuner monsters as Materials: You can Special Summon 1 FIRE Fiend-Type monster from your Deck in Defense Position." where id=21142671
;update texts set name="Ancient Gear", desc="If you control an ""Ancient Gear"", you can Special Summon this card (from your hand) in face-up Attack Position." where id=31557782
;update texts set name="Return", desc="When your opponent adds a card(s) from the Graveyard to their hand: They must shuffle 1 of those cards into their Deck." where id=47247413
;update texts set name="Pharaoh's Servant", desc="An apparition of those said to formerly serve the Pharaoh. It has tremendous loyalty that does not waiver." where id=52550973
;update texts set name="Labyrinth of Nightmare", desc="Once per turn, during each player's End Phase: Change the battle positions of all face-up monsters the turn player controls." where id=66526672
;update texts set name="Lillybot", desc="When this card is Normal Summoned or flipped face-up: You can target 1 ""Orbital 7"" in your Graveyard; Special Summon that target in face-up Attack Position or face-down Defense Position. Once per turn: You can Tribute any number of Machine-Type monsters; Special Summon an equal number of ""Photon"" and/or ""Galaxy"" monsters from your hand." where id=68812773
;update texts set name="Orbital 7", desc="When this card is flipped face-up: Place 1 You Got It Boss! Counter on it. You can remove all You Got It Boss! Counters on this card; its ATK becomes 2000. After you change this card's ATK with this effect, it cannot attack your opponent directly for the rest of this turn, and is sent to the Graveyard during the End Phase. You can Tribute this card to target 1 ""Photon"" or ""Galaxy"" monster in your Graveyard; add that target to your hand." where id=71071546
;update texts set name="Princess Cologne", desc="2 Level 4 monsters
When this card is Xyz Summoned: You can target 1 ""Box of Friends"" in your Graveyard; Special Summon that target. If you control another monster, your opponent cannot target this card with cards, effects, or for attacks. If a face-up Normal Monster(s) you control is destroyed by battle or by card effect and sent to the Graveyard: You can detach 1 Xyz Material from this card; Special Summon 1 Normal Monster from your Deck or Graveyard in face-up Defense Position." where id=75574498
;update texts set name="Light of Destruction", desc="When an opponent's card effect sends a card(s) from their Deck to the Graveyard, send the top 3 cards of their Deck to the Graveyard." where id=83027236
;update texts set name="Generation Force", desc="If you control an Xyz Monster: Add 1 ""Xyz"" card from your Deck to your hand." where id=87890143
;update texts set name="Halfway to Forever", desc="Target 2 monsters in your Graveyard; Special Summon both targets, but they have their effects negated. Immediately after this effect resolves, Xyz Summon 1 LIGHT ""Utopia"" or ""Utopic"" Xyz Monster using only those 2 monsters." where id=100213057;