update texts set name="Zoodiac Kataroost", desc="If this card is destroyed by battle or card effect: You can target 1 ""Zoodiac"" card in your Graveyard, except ""Zoodiac Kataroost""; shuffle it into the Deck. An Xyz Monster whose original Type is Beast-Warrior and has this card as Xyz Material gains this effect.
● During either player's turn, when your opponent activates a monster effect that targets this card: You can detach 1 Xyz Material from this card; negate the activation." where id=20155904
;update texts set name="Baobaboon", desc="If this card is Normal or Special Summoned: You can draw 1 card, then place 1 card from your hand on either the top or bottom of your Deck. If this card is destroyed by battle or card effect: You can Special Summon any number of ""Baobaboon"" from your Deck." where id=55705473
;update texts set name="Number 22: Zombiestein", desc="2 Level 8 DARK monsters
Must be Xyz Summoned and cannot be Special Summoned by other ways. Once per turn, during either player's turn: You can detach 1 Xyz Material from this card and send 1 card from your hand to the Graveyard, then target 1 face-up card your opponent controls; change this card to Defense Position, and if you do, that face-up card has its effects negated until the end of this turn." where id=73445448
;update texts set name="Masked HERO Blast", desc="Must be Special Summoned with ""Mask Change"" and cannot be Special Summoned by other ways. If this card is Special Summoned: You can target 1 face-up monster your opponent controls; its ATK becomes half its current ATK. Once per turn, during either player's turn: You can pay 500 LP, then target 1 Spell/Trap Card your opponent controls; return it to the hand." where id=89870349
;update texts set name="The Legendary Fisherman", desc="While ""Umi"" is on the field, this card is unaffected by Spell effects and cannot be targeted for attacks, but does not prevent your opponent from attacking you directly." where id=03643300
;update texts set name="Fluffal Leo", desc="When this card declares an attack: It gains 500 ATK until the end of the Battle Phase." where id=66457138
;update texts set name="Mayosenju Daibak", desc="Pendulum Effect
When a ""Yosenju"" monster you control declares an attack: You can have that attacking monster gain 300 ATK until the end of the Battle Phase.

Monster Effect
Cannot be Special Summoned, except by Pendulum Summon. This card's Pendulum Summon cannot be negated. If this card is Normal or Special Summoned: You can target up to 2 cards on the field; return them to the hand. Once per turn, during the End Phase, if this card was Special Summoned this turn: Return it to the hand." where id=93368494
;update texts set name="Yosenju Kama 1", desc="If this card is Normal Summoned, you can: Immediately after this effect resolves, Normal Summon 1 ""Yosenju"" monster from your hand, except ""Yosenju Kama 1"". If you control another ""Yosenju"" monster: You can target 1 face-up card your opponent controls; return it to the hand. This effect can only be used once while this card is face-up on the field. Once per turn, during the End Phase, if this card was Normal Summoned this turn: Return it to the hand." where id=65247798
;update texts set name="Yosenju Kama 2", desc="If this card is Normal Summoned, you can: Immediately after this effect resolves, Normal Summon 1 ""Yosenju"" monster from your hand, except ""Yosenju Kama 2"". This card can attack your opponent directly, but when it does so using this effect, the battle damage inflicted to your opponent is halved. Once per turn, during the End Phase, if this card was Normal Summoned this turn: Return it to the hand." where id=92246806
;update texts set name="Yosenju Kama 3", desc="If this card is Normal Summoned, you can: Immediately after this effect resolves, Normal Summon 1 ""Yosenju"" monster from your hand, except ""Yosenju Kama 3"". When another ""Yosenju"" monster you control inflicts battle damage to your opponent: You can add 1 ""Yosenju"" card from your Deck to your hand, except ""Yosenju Kama 3"". You can only use this effect of ""Yosenju Kama 3"" once per turn. Once per turn, during the End Phase, if this card was Normal Summoned this turn: Return it to the hand." where id=28630501
;update texts set name="Yosenju Shinchu L", desc="Pendulum Effect
If a ""Yosenju"" monster(s) you control would be destroyed by battle or card effect, you can destroy this card instead.

Monster Effect
If this card is Normal Summoned: Change it to Defense Position. Your opponent cannot target ""Yosenju"" monsters you control with card effects, except this one." where id=65025250
;update texts set name="Yosenju Shinchu R", desc="Pendulum Effect
Once per turn, if you have a ""Yosenju"" card in your other Pendulum Zone: You can make this card's Pendulum Scale become 11 until the end of this turn, also you cannot Special Summon monsters for the rest of this turn, except ""Yosenju"" monsters (even if this card leaves the field).

Monster Effect
If this card is Normal Summoned: Change it to Defense Position. Monsters your opponent controls cannot target face-up ""Yosenju"" monsters for attacks, except this one." where id=91420254
;update texts set name="Superheavy Samurai Big Waraji", desc="If you have no Spell/Trap Cards in your Graveyard, you can Special Summon this card (from your hand). After this card was Special Summoned this way, you cannot Special Summon monsters for the rest of this turn, except ""Superheavy Samurai"" monsters. This card can be treated as 2 Tributes for the Tribute Summon of a Machine-Type monster." where id=36523152
;update texts set name="Superheavy Samurai Gigagloves", desc="If this card is sent to the Graveyard, and you have no Spell/Trap Cards in your Graveyard: You can look at 5 cards from the top of your Deck, then place them on the top of the Deck in any order. When an opponent's monster declares a direct attack: You can banish this card from your Graveyard; excavate the top card of your Deck, and if it is a ""Superheavy Samurai"" monster, add it to your hand, and if you do, the attacking monster's ATK becomes 0. Otherwise, send it to the Graveyard." where id=62017867
;update texts set name="Superheavy Samurai Battleball", desc="If all monsters you control are ""Superheavy Samurai"" monsters, and you have no Spell/Trap Cards in your Graveyard: You can target 1 face-up monster your opponent controls that has a Level; send both it and this card from the field to the Graveyard, then Special Summon from your Extra Deck 1 ""Superheavy Samurai"" Synchro Monster whose Level equals the total original Levels of those 2 monsters in the Graveyard. (This Special Summon is treated as a Synchro Summon.) You can only use this effect of ""Superheavy Samurai Battleball"" once per turn." where id=09402966
;update texts set name="Superheavy Samurai Soulbuster Gauntlet", desc="You can target 1 ""Superheavy Samurai"" monster you control; equip this monster from your hand or field to that target. It gains 400 DEF. During either player's Damage Step, when a Defense Position ""Superheavy Samurai"" monster you control battles an opponent's monster, and you have no Spell/Trap Cards in your Graveyard: You can send this card from your hand to the Graveyard; your battling monster's DEF becomes double its original DEF until the end of this turn." where id=35800511
;update texts set name="Soprano the Melodious Songstress", desc="When this card is Special Summoned: You can target 1 ""Melodious"" monster in your Graveyard, except ""Soprano the Melodious Songstress""; add it to your hand. You can only use this effect of ""Soprano the Melodious Songstress"" once per turn. Once per turn: You can Fusion Summon 1 ""Melodious"" Fusion Monster from your Extra Deck, using monsters you control as Fusion Materials, including this card." where id=62895219
;update texts set name="Fluffal Sheep", desc="If you control a ""Fluffal"" monster, except ""Fluffal Sheep"", you can Special Summon this card (from your hand). You can return 1 other ""Fluffal"" monster you control to the hand; Special Summon 1 ""Edge Imp"" monster from your hand or Graveyard. You can only use this effect of ""Fluffal Sheep"" once per turn." where id=98280324
;update texts set name="Edge Imp Saw", desc="When this card is Normal Summoned: You can send 1 ""Fluffal"" monster from your hand to the Graveyard; draw 2 cards, then place 1 card from your hand on either the top or bottom of your Deck. You can only use this effect of ""Edge Imp Saw"" once per turn." where id=34688023
;update texts set name="Performapal Thunderhino", desc="Monsters your opponent controls cannot target face-up ""Performapal"" monsters for attacks, except this one. If a ""Performapal"" card(s) you control, except ""Performapal Thunderhino"", would be destroyed by battle or card effect while this card is in your Graveyard, you can banish this card instead." where id=70458081
;update texts set name="Xiangke Magician", desc="Pendulum Effect
Once per turn: You can target 1 face-up Xyz Monster you control; this turn, you can use it as an Xyz Material for an Xyz Summon using its Rank as if it were a Level (even if this card leaves the field).

Monster Effect
Once per turn, during either player's turn: You can target 1 LIGHT monster on the field; that face-up monster has its effects negated until the end of this turn." where id=71692913
;update texts set name="Xiangsheng Magician", desc="Pendulum Effect
Once per turn: You can target 1 face-up Xyz Monster you control, and 1 Level 5 or higher monster you control; that Xyz Monster's Rank becomes equal to the Level of that Level 5 or higher monster, until the end of this turn (even if this card leaves the field). While you control more cards than your opponent does, this card's Pendulum Scale becomes 4.

Monster Effect
Your opponent takes no battle damage from attacks involving this card. Once per turn: You can target 1 other face-up monster you control; this card's ATK becomes equal to that monster's current ATK, until the end of this turn." where id=17086528
;update texts set name="Performapal Drummerilla", desc="Pendulum Effect
Once per turn, when an attack is declared involving a monster you control and an opponent's monster: You can target that monster you control; it gains 600 ATK until the end of the Battle Phase (even if this card leaves the field).

Monster Effect
If there are no monsters on the field, you can Normal Summon this card without Tributing. If this card is Normal Summoned without Tributing, its Level becomes 4. Once per turn, when an attack is declared involving a monster you control and an opponent's monster: You can target that monster you control; it gains 600 ATK until the end of the Battle Phase." where id=70479321
;update texts set name="Opera the Melodious Diva", desc="Cannot attack the turn it is Normal Summoned or flipped face-up. If this card is sent to the Graveyard as a Fusion Material for a Fusion Summon: You can activate this effect; for the rest of this turn, ""Melodious"" monsters you control cannot be destroyed by battle or card effects." where id=43268675
;update texts set name="Crystal Rose", desc="Once per turn: You can send 1 ""Gem-Knight"" or ""Melodious"" monster from your hand or Deck to the Graveyard, and if you do, this card's name becomes the sent monster's name, until the End Phase. If this card is in your Graveyard: You can banish 1 Fusion Monster from your Graveyard; Special Summon this card in Defense Position. You can only use this effect of ""Crystal Rose"" once per turn." where id=79531196
;update texts set name="Speedroid Terrortop", desc="If you control no monsters, you can Special Summon this card (from your hand). When this card is Normal or Special Summoned: You can add 1 ""Speedroid"" monster from your Deck to your hand, except ""Speedroid Terrortop"". You can only use this effect of ""Speedroid Terrortop"" once per turn." where id=81275020
;update texts set name="Speedroid Tri-Eyed Dice", desc="During your opponent's turn: You can banish this card from your Graveyard; negate the next attack this turn from a monster your opponent controls (this is a Quick Effect)." where id=27660735
;update texts set name="Speedroid Double Yoyo", desc="When this card is Normal Summoned: You can target 1 Level 3 or lower ""Speedroid"" monster in your Graveyard; Special Summon it." where id=53054833
;update texts set name="Performapal Secondonkey", desc="When this card is Normal or Special Summoned: You can send 1 ""Performapal"" monster from your Deck to the Graveyard, except ""Performapal Secondonkey"". If you have 2 cards in your Pendulum Zones, you can add it to your hand instead." where id=15978426
;update texts set name="D/D Swirl Slime", desc="If this card is in your hand: You can Fusion Summon 1 ""D/D/D"" Fusion Monster from your Extra Deck, using monsters from your hand as Fusion Materials, including this card. You can banish this card from your Graveyard; Special Summon 1 ""D/D"" monster from your hand. You can only use each effect of ""D/D Swirl Slime"" once per turn." where id=45206713
;update texts set name="D/D Necro Slime", desc="If this card is in your Graveyard: You can Fusion Summon 1 ""D/D/D"" Fusion Monster from your Extra Deck, by banishing Fusion Materials listed on it from your Graveyard, including this card. You can only use this effect of ""D/D Necro Slime"" once per turn." where id=72291412
;update texts set name="The Legendary Fisherman III", desc="Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by Tributing 1 ""The Legendary Fisherman"", and cannot be Special Summoned by other ways. When this card is Special Summoned: You can banish all monsters your opponent controls, also this card cannot attack this turn. Cannot be destroyed by battle or card effects, also unaffected by Spell/Trap effects. Once per turn: You can return as many of your opponent's banished cards as possible to their Graveyard, and if you do, the first battle or effect damage your opponent takes this turn becomes doubled." where id=44968687
;update texts set name="D/D/D Oblivion King Abyss Ragnarok", desc="Pendulum Effect
If you Special Summon a ""D/D"" monster(s), except during the Damage Step: You can target 1 ""D/D"" monster in your Graveyard; any battle damage your opponent takes becomes halved for the rest of this turn, also Special Summon that monster, and if you do, take 1000 damage. You can only use this effect of ""D/D/D Oblivion King Abyss Ragnarok"" once per turn.

Monster Effect
If this card is Normal or Special Summoned: You can target 1 ""D/D/D"" monster in your Graveyard; Special Summon it. You can only use this effect of ""D/D/D Oblivion King Abyss Ragnarok"" once per turn. Once per turn: You can Tribute 1 other ""D/D"" monster, then target 1 monster your opponent controls; banish it." where id=74069667
;update texts set name="Solo the Melodious Songstress", desc="If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 ""Melodious"" monster from your Deck, except ""Solo the Melodious Songstress""." where id=14763299
;update texts set name="Score the Melodious Diva", desc="During damage calculation (in either player's turn), if a ""Melodious"" monster you control battles an opponent's monster: You can send this card from your hand to the Graveyard; change that opponent's monster's ATK and DEF to 0, until the end of this turn." where id=41767843
;update texts set name="Performapal Odd-Eyes Light Phoenix", desc="Pendulum Effect
When an opponent's monster declares a direct attack while you have a card in your other Pendulum Zone: You can destroy the card in your other Pendulum Zone, and if you do, Special Summon this card.

Monster Effect
During either player's turn: You can Tribute this card, then target 1 ""Performapal"" monster you control; it gains 1000 ATK until the end of this turn." where id=59762399
;update texts set name="Performapal Odd-Eyes Unicorn", desc="Pendulum Effect
Once, while this card is in your Pendulum Zone, when an ""Odd-Eyes"" monster you control declares an attack: You can target 1 other ""Performapal"" monster you control; that attacking monster gains ATK equal to the original ATK of the targeted monster on the field, until the end of the Battle Phase (even if this card leaves the field).

Monster Effect
When this card is Normal or Special Summoned: You can target 1 ""Performapal"" monster in your Graveyard; gain LP equal to its ATK." where id=86157908
;update texts set name="Performapal Fireflux", desc="Pendulum Effect
Once per turn, when an opponent's monster declares an attack: You can Tribute 1 ""Performapal"" monster; negate the attack, then end the Battle Phase.

Monster Effect
If a ""Performapal"" or ""Odd-Eyes"" monster you control attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step." where id=12255007
;update texts set name="Schuberta the Melodious Maestra", desc="2 ""Melodious"" monsters
During either player's turn: You can target up to 3 cards in any Graveyard(s); banish them, and if you do, this card gains 200 ATK for each. This effect can only be used once while this card is face-up on the field." where id=57594700
;update texts set name="Bloom Diva the Melodious Choir", desc="1 ""Melodious Maestra"" monster + 1 ""Melodious"" monster
Cannot be destroyed by battle or card effects, also you take no battle damage from attacks involving this card. If this card battles a Special Summoned monster, after damage calculation: You can inflict damage to your opponent equal to the difference between the original ATK of that opponent's monster and this card, and if you do, destroy that opponent's monster." where id=84988419
;update texts set name="Frightfur Leo", desc="""Edge Imp Saw"" + 1 ""Fluffal"" monster
Must be Fusion Summoned and cannot be Special Summoned by other ways. You can target 1 face-up monster your opponent controls; destroy it, and if you do, inflict damage to your opponent equal to the destroyed monster's original ATK. You can only use this effect of ""Frightfur Leo"" once per turn. This card cannot attack your opponent directly during the turn you activate this effect." where id=10383554
;update texts set name="Frightfur Sheep", desc="""Edge Imp Chain"" + 1 ""Fluffal"" monster
If this card battles, your opponent cannot activate cards or effects until the end of the Damage Step. If this card is destroyed by battle and sent to the Graveyard, or if this card in your possession is destroyed by an opponent's card effect and sent to your Graveyard: You can Special Summon this card, and if you do, it gains 800 ATK. You can only use this effect of ""Frightfur Sheep"" once per turn." where id=57477163
;update texts set name="Frightfur Chimera", desc="3 ""Frightfur"" monsters
Must be Fusion Summoned and cannot be Special Summoned by other ways. If this card battles, your opponent cannot activate cards or effects until the end of the Damage Step. When this card destroys an opponent's monster by battle and sends it to the Graveyard: You can Special Summon that monster to your field, but its ATK is halved. You can only use this effect of ""Frightfur Chimera"" once per turn. This card gains 300 ATK for each monster you control that is owned by your opponent." where id=83866861
;update texts set name="D/D/D Oracle King d'Arc", desc="2 ""D/D"" monsters
Any effect that would inflict damage to you makes you gain that much LP, instead." where id=82956492
;update texts set name="Bloom Prima the Melodious Choir", desc="1 ""Melodious Maestra"" monster + 1 or more ""Melodious"" monsters
This card gains 300 ATK for each Fusion Material used for its Fusion Summon. This card can make a second attack during each Battle Phase. If this Fusion Summoned card is sent to the Graveyard: You can target 1 ""Melodious"" monster in your Graveyard; add it to your hand." where id=24672164
;update texts set name="Superheavy Samurai Ogre Shutendoji", desc="1 Machine-Type Tuner + 1 or more non-Tuner ""Superheavy Samurai"" monsters
This card can attack while in face-up Defense Position. If it does, apply its DEF for damage calculation. When this card is Synchro Summoned, while you have no Spell/Trap Cards in your Graveyard: You can destroy all Spell and Trap Cards your opponent controls." where id=36953371
;update texts set name="Hi-Speedroid Kendama", desc="1 Tuner + 1 or more non-Tuner monsters
If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. You can only use each of the following effects of ""Hi-Speedroid Kendama"" once per turn.
● You can banish 1 Machine-Type monster from your Graveyard; inflict 500 damage to your opponent.
● If this card is in your Graveyard and you control no cards: You can Special Summon this card. You cannot Normal Summon/Set the turn you activate this effect." where id=97007933
;update texts set name="Odd-Eyes Rebellion Dragon", desc="Pendulum Effect
Once per turn, if you have no cards in your other Pendulum Zone: You can place 1 Pendulum Monster from your Deck in your Pendulum Zone.

Monster Effect
2 Level 7 Dragon-Type monsters
If you can Pendulum Summon Level 7, you can Pendulum Summon this face-up card in your Extra Deck. If this card is Xyz Summoned by using an Xyz Monster as a Material: Destroy as many Level 7 or lower monsters your opponent controls as possible, inflict 1000 damage to your opponent for each card destroyed, and if you do, this card can make 3 attacks during each Battle Phase this turn. If this card in the Monster Zone is destroyed by battle or card effect: You can destroy as many cards in your Pendulum Zones as possible (min. 1), and if you do, place this card in your Pendulum Zone." where id=45627618
;update texts set name="D/D/D Duo-Dawn King Kali Yuga", desc="2 Level 8 ""D/D"" monsters
After this card is Xyz Summoned, for the rest of this turn, other cards and their effects cannot be activated on the field, and other cards' effects on the field are negated. Once per turn, during either player's turn: You can detach 1 Xyz Material from this card; destroy all Spell and Trap Cards on the field. You can detach 1 Xyz Material from this card, then target 1 ""Dark Contract"" Spell/Trap Card in your Graveyard; Set that target." where id=15939229
;update texts set name="Frightfur Fusion", desc="Fusion Summon 1 ""Frightfur"" Fusion Monster from your Extra Deck, by banishing Fusion Materials listed on it from your field or Graveyard. You can only activate 1 ""Frightfur Fusion"" per turn." where id=06077601
;update texts set name="Pianissimo", desc="Target 1 face-up monster you control; this turn, that face-up monster's original ATK becomes 100, also that face-up monster cannot be destroyed by battle or card effects." where id=70899775
;update texts set name="Speed Recovery", desc="Target 1 ""Speedroid"" monster in your Graveyard; Special Summon it. During your Main Phase, except the turn this card was sent to the Graveyard: You can banish this card from your Graveyard, then target 1 ""Speedroid"" monster in your Graveyard; add it to your hand." where id=88204302
;update texts set name="Urgent Tuning", desc="During the Battle Phase: Immediately after this effect resolves, Synchro Summon 1 Synchro Monster using monsters you control." where id=94634433
;update texts set name="Yosenjus' Secret Move", desc="When a Spell/Trap Card, or monster effect, is activated while you control at least 1 ""Yosenju"" card, and all face-up monsters you control are ""Yosenju"" monsters: Negate the activation, and if you do, destroy that card." where id=54903668;